package com.relative.quski.enums;

public enum ActividadEnum {
	NEGOCIACION,
	GESTION_CLIENTE,
	GENERAR_CREDITO,
	APROBACION_FABRICA,
	COTIZADOR,
	GENERAR_NOVACION,
	ACTUALIZACION_DATOS_CLIENTE,
	FORMULARIO_NOVACIONES_HABILITANTES,
	APROBACION_FABRICA_NOVACIONES,
	SOLICITUD_DEVOLUCION,
	APROBACION_SOLICITUD_DEVOLUCION,
	ENTREGA_RECEPCION,
	APROBACION_DEVOLUCION_VERIFICACION_FIRMADAS
}
