package com.relative.quski.enums;

public enum ActividadEnum {
	COTIZADOR,
	
	NEGOCIACION,
	GESTION_CLIENTE,
	GENERAR_CREDITO,
	APROBACION_FABRICA,
	
	GENERAR_NOVACION,
	ACTUALIZACION_DATOS_CLIENTE,
	FORMULARIO_NOVACIONES_HABILITANTES,
	APROBACION_FABRICA_NOVACIONES,
	
	SOLICITUD_DE_DEVOLUCION,
	APROBACION_SOLICITUD_DE_DEVOLUCION,
	ENTREGA_RECEPCION,
	APROBACION_DEVOUCION_VERIFICACION_FIRMADAS
}
