package com.relative.quski.enums;

public enum EstadoProcesoEnum {
	NEGOCIACION,
	APROBADO,
	PENDIENTE_ARRIBO,
	PENDIENTE_APROBACION,
	CUSTODIA_AGENCIA,
	DEVUELTO,
	RECHAZADO,
	CREADO,
	CANCELADO,
	PENDIENTE_EXCEPCION,
	EXCEPCIONADO,
	FINALIZADO
}
