package com.relative.quski.enums;

public enum ProcesoEnum {
	
	NUEVO,
	RENOVACION,
	DEVOLUCION,
	COTIZACION,
	CANCELACION_DEVOLUCION,
	PAGO,
	VERIFICACION_TELEFONICA,
	COMPROMISO_PAGO,
	CAMBIO_COMPROMISO_PAGO,
}
